export const templates = [
  {
    id: 'corporate-blue',
    name: 'Corporate Blue',
    category: 'Corporate',
    thumbnail: null,
    bgColor: '#1e3a5f',
    accentColor: '#4F46E5',
    textColor: '#ffffff',
    description: 'Professional corporate template with navy blue background',
  },
  {
    id: 'corporate-black',
    name: 'Corporate Black',
    category: 'Corporate',
    thumbnail: null,
    bgColor: '#1a1a1a',
    accentColor: '#FFD700',
    textColor: '#ffffff',
    description: 'Premium black corporate design with gold accents',
  },
  {
    id: 'green-professional',
    name: 'Green Professional',
    category: 'Corporate',
    thumbnail: null,
    bgColor: '#065f46',
    accentColor: '#10b981',
    textColor: '#ffffff',
    description: 'Nature-inspired professional green design',
  },
  {
    id: 'tech-modern',
    name: 'Tech Modern',
    category: 'Modern',
    thumbnail: null,
    bgColor: '#0f172a',
    accentColor: '#7c3aed',
    textColor: '#ffffff',
    description: 'Sleek dark tech-inspired modern design',
  },
  {
    id: 'floral-creative',
    name: 'Floral Creative',
    category: 'Creative',
    thumbnail: null,
    bgColor: '#fdf2f8',
    accentColor: '#ec4899',
    textColor: '#1f2937',
    description: 'Elegant floral creative design with pink accents',
  },
  {
    id: 'minimal-white',
    name: 'Minimal White',
    category: 'Minimal',
    thumbnail: null,
    bgColor: '#ffffff',
    accentColor: '#4F46E5',
    textColor: '#1f2937',
    description: 'Clean minimalist white design with subtle accents',
  },
]

export const getTemplateById = (id) => templates.find((t) => t.id === id)
